### ISSUE TITLE
Text between double brackets in code block have disappeared

### ISSUE THREAD

**Issue by hoonti06** [jeffreytse/jekyll-spaceship#68]
Hi, I have some problem to convert YAML code block.

I want to convert code block as below.
~~~
```yml
- name: Upload & release
   uses: mnao305/chrome-extension-upload@2.1.0
   with:
      file-path: frontend/extension/build.zip
      extension-id: 'abcdefghijklmnopqrstuvwxyzabcdef'
      client-id: ${{ secrets.GOOGLE_CLIENT_ID }}
      refresh-token: ${{ secrets.GOOGLE_REFRESH_TOKEN }}
```
~~~

but, result is not I expected.
![](https://user-images.githubusercontent.com/17792043/144971962-dfbadb55-83b9-4544-876a-75a8eb889436.png)

`{{ secrets.GOOGLE_CLIENT_ID }}` and `{{ secrets.GOOGLE_REFRESH_TOKEN }}` have disappeared in rendered HTML.
