### ISSUE TITLE
How: Escaping dollar signs to get $

### ISSUE THREAD

**Issue by jlconlin** [jeffreytse/jekyll-spaceship#75]
I like how jekyll-spaceship bundles and configures MathJax; it makes my life easier. However, since I installed spaceship, when I use a dollar sign `$`, it automatically assumes I'm going to be in LaTeX mode---even if I escape it, `\$`. I know there is an option for MathJax called `processEscapes` that allows me to escape the dollar sign when I want to have a dollar sign (instead of enter LaTeX mode), but I'm not sure how to enable this with jekyll-spaceship.

**Comment by ani-per** [comment]
You can disable dollar sign inline parsing entirely by adding this to your `_config.yml`:

```yaml

jekyll-spaceship:
  mathjax-processor:
    config:
      tex:
        inlineMath:
          - ['\(','\)']
```

To turn on `processEscapes`, use a similar setup:

```yaml

jekyll-spaceship:
  mathjax-processor:
    config:
      tex:
        processEscapes: true
```
