### ISSUE TITLE
Which mermaid themes does it supported?

### ISSUE THREAD

**Issue by tristone13th** [jeffreytse/jekyll-spaceship#84]
I didn't find any further documentation in the readme about the mermaid themes, can you list them out for my reference?

**Comment by jeffreytse** [comment]
Hi @tristone13th 

The mermaid can be configured by users, all options are matched to [mermaid official document](https://mermaid-js.github.io/mermaid/#/theming), you can learn options by mermaid official document.

```yml
mermaid-processor:
    mode: default  # mode value 'pre-fetch' for fetching image at building stage
    css:
      class: mermaid
    syntax:
      code: 'mermaid!'
      custom: ['@startmermaid', '@endmermaid']
    config:
      theme: default
```

All options under `config` are the same as the first line under `init`:

```mermaid!
%%{init: {'theme':'forest'}}%%
graph TD
    a --> b
```

Above code is rendered as below:

```mermaid
%%{init: {'theme':'forest'}}%%
graph TD
    a --> b
```

Thanks & Regards
